### ISSUE TITLE
La funcion $data->getCondDomiRuc(), solo devuelve "true"

### ISSUE THREAD

**Issue by ebjalbert** [thegreenter/consulta-cpe#1]
La funcion $data->getCondDomiRuc(), solo devuelve "true".
En la documentación muestran otros códigos:
Condición de Domicilio del Contribuyente (Códigos devuelto en $data->getCondDomiRuc())
`{ "estadoCp": "1", "estadoRuc": "00", "condDomiRuc": true }`

**Comment by giansalex** [comment]
@ebjalbert gracias por reportarlo, la corrección esta disponible en la versión `v1.0.1`
